#!/usr/bin/env bash
# scripts/run-e2e-full-lab.sh
#
# End-to-end greenfield proof:
#   1. Purge and recreate the KVM lab
#   2. Converge multi-instance site (super DG + duper + fluff) at baseline 19.31
#   3. Install/patch dbhome_2 @ 19.31 for standalone DBs (no Restart switch)
#   4. Dual-home upgrade standalone DBs to 19.32 (prepare home2 → cutover →
#      rebuild home1 → cutover back)
#   5. Super DG: skip standby-first for OJVM+RU combo (apply combos together via
#      dual-home/downtime; SF only for fully SF-eligible media)
#   6. Warm Data Guard switchover cycle
#   7. Power-cycle and prove automatic Oracle/observer startup
#   8. Full pytest suite
#
# Usage:
#   scripts/run-e2e-full-lab.sh
#   SKIP_LAB_RECREATE=1 scripts/run-e2e-full-lab.sh   # reuse existing VMs
#   SKIP_TESTS=1 scripts/run-e2e-full-lab.sh
#   SKIP_SUPER_UPGRADE=0  # reserved; SF on combo is not the default path

set -euo pipefail

REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "${REPO_DIR}"

LOG="${E2E_LOG:-/tmp/e2e-full-lab.log}"
exec > >(tee -a "${LOG}") 2>&1

echo "======== E2E START $(date -Is) log=${LOG} ========"

export ANSIBLE_LOCAL_TEMP="${ANSIBLE_LOCAL_TEMP:-/tmp/ansible-local}"
export ANSIBLE_SSH_CONTROL_PATH_DIR="${ANSIBLE_SSH_CONTROL_PATH_DIR:-/tmp/ansible-cp}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-/tmp/ansible-cache}"
export LAB_ROOT_DISK_SIZE="${LAB_ROOT_DISK_SIZE:-250G}"
# System QEMU cannot traverse private $HOME; prefer the libvirt-readable stage.
if [ -z "${SOURCES_DIR:-}" ]; then
  if [ -d /var/lib/libvirt/ansible-oracle-sources ]; then
    export SOURCES_DIR=/var/lib/libvirt/ansible-oracle-sources
  else
    export SOURCES_DIR="${HOME}/sources/oracle"
  fi
fi

INV="${INVENTORY:-inventory/hosts.yml}"
SMOKE="inventory/examples/multi-instance-smoke.yml"
PB="${ANSIBLE_PLAYBOOK:-}"
if [ -z "${PB}" ]; then
  if [ -x "${REPO_DIR}/.venv/bin/ansible-playbook" ]; then
    PB="${REPO_DIR}/.venv/bin/ansible-playbook"
  else
    PB="$(command -v ansible-playbook)"
  fi
fi

# Baseline 19.31 media (inventory defaults)
BASE_DB_ZIP="/u01/stage/p39062931_190000_Linux-x86-64.zip"
BASE_DB_COMPONENT="39062931/39034528"
BASE_RU="19.31.0.0.260421"
BASE_PATCH_ID="39034528"

# Upgrade 19.32 media
UPG_DB_ZIP="/u01/stage/p39618649_190000_Linux-x86-64.zip"
UPG_DB_COMPONENT="39618649/39472050"

SKIP_LAB_RECREATE="${SKIP_LAB_RECREATE:-0}"
SKIP_TESTS="${SKIP_TESTS:-0}"
SKIP_SUPER_UPGRADE="${SKIP_SUPER_UPGRADE:-0}"

step() {
  echo
  echo "======== $(date -Is) $* ========"
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

run_pb() {
  echo "+ ${PB} $*"
  "${PB}" "$@"
}

# Standalone-only vars for dual-home prepare (rejects DG instances).
write_standalone_vars() {
  local current_home="${1:-dbhome_1}"
  local out="${2:-/tmp/e2e-standalone-dual.yml}"
  cat >"${out}" <<EOF
# Generated by run-e2e-full-lab.sh — standalone dual-home targets only.
oracle_network_dataguard_enabled: true
oracle_network_interface: eth0
oracle_lab_host_map_mode: dataguard
oracle_db_manage_apply_instance_overrides_require_dataguard: false
oracle_restart_apply_instance_overrides_require_dataguard: false
oracle_service_apply_instance_overrides_require_dataguard: false

oracle_instances:
  - name: duper
    oracle_base: /duper/app/oracle
    db_homes:
      - suffix: dbhome_1
        current: $([ "${current_home}" = "dbhome_1" ] && echo true || echo false)
      - suffix: dbhome_2
        current: $([ "${current_home}" = "dbhome_2" ] && echo true || echo false)
    gi_base: /grid
    gi_homes:
      - suffix: 19c/gi_home1
        current: true
      - suffix: 19c/gi_home2
        current: false
    dirs:
      data: /duper/d01
      archive: /duper/a01
      flashback: /duper/f01
      redo: /duper/r01
    dataguard: false
    archivelog: true
    flashback: false
    force_logging: true
    memory:
      sga_target: 1G
      pga_aggregate_target: 512M
    listener_vip: duperdb.domain.is
    listener_ip: 192.168.87.22
    listener_port: 1522
    service_name: duper_svc

  - name: fluff
    oracle_base: /fluff/app/oracle
    db_homes:
      - suffix: dbhome_1
        current: $([ "${current_home}" = "dbhome_1" ] && echo true || echo false)
      - suffix: dbhome_2
        current: $([ "${current_home}" = "dbhome_2" ] && echo true || echo false)
    gi_base: /grid
    gi_homes:
      - suffix: 19c/gi_home1
        current: true
      - suffix: 19c/gi_home2
        current: false
    dirs:
      data: /fluff/d01
      archive: /fluff/a01
      flashback: /fluff/f01
      redo: /fluff/r01
    dataguard: false
    archivelog: false
    flashback: false
    force_logging: false
    memory:
      sga_target: 1G
      pga_aggregate_target: 512M
    listener_vip: fluffdb.domain.is
    listener_ip: 192.168.87.23
    listener_port: 1523
    service_name: fluff_svc

oracle_lab_guest_hosts:
  - ip: 192.168.87.11
    names: superdb1.domain.is superdb1
    modes: [standalone, dataguard]
  - ip: 192.168.87.12
    names: superdb2.domain.is superdb2
    modes: [standalone, dataguard]
  - ip: 192.168.87.13
    names: observer.domain.is observer
    modes: [standalone, dataguard]
  - ip: 192.168.87.22
    names: duperdb.domain.is duperdb
    modes: [standalone, dataguard]
  - ip: 192.168.87.23
    names: fluffdb.domain.is fluffdb
    modes: [standalone, dataguard]
  - ip: 192.168.87.31
    names: superdc1.domain.is superdc1
    modes: [dataguard]
  - ip: 192.168.87.32
    names: superdc2.domain.is superdc2
    modes: [dataguard]

oracle_lab_listener_vips:
  - ip: 192.168.87.22
    names: duperdb.domain.is duperdb
  - ip: 192.168.87.23
    names: fluffdb.domain.is fluffdb
  - ip: 192.168.87.31
    names: superdc1.domain.is superdc1
  - ip: 192.168.87.32
    names: superdc2.domain.is superdc2
EOF
  echo "${out}"
}

# ── 1. Lab recreate ────────────────────────────────────────────────────
if [ "${SKIP_LAB_RECREATE}" != "1" ]; then
  step "1/8 Lab purge + recreate"
  ./lab/scripts/lab-down.sh --purge
  ./lab/scripts/lab-up.sh
  ./lab/scripts/update-hosts.sh --dg --multi || true
else
  step "1/8 SKIP lab recreate (SKIP_LAB_RECREATE=1)"
  ./lab/scripts/lab-up.sh
  ./lab/scripts/update-hosts.sh --dg --multi || true
fi

[ -f "${INV}" ] || fail "inventory missing: ${INV}"

# ── 2. Greenfield site at 19.31 (no pytest yet) ────────────────────────
step "2/8 Multi-instance site converge @ 19.31 (playbooks 00–08 + patch)"

# site.yml order without 99-test so we control upgrade before suite.
SITE_PLAYS=(
  playbooks/00-prep-os.yml
  playbooks/01-install-grid.yml
  playbooks/02-install-dbhome.yml
  playbooks/03-create-instance.yml
  playbooks/04-register-restart.yml
  playbooks/05-dataguard.yml
  playbooks/04-register-restart.yml
  playbooks/06-observer.yml
  playbooks/08-client-availability.yml
  playbooks/07-patch.yml
  playbooks/07-patch-grid.yml
)

COMMON_E=(
  -i "${INV}"
  -e @"${SMOKE}"
  -e oracle_gi_install_enabled=true
  -e oracle_network_dataguard_enabled=true
  -e oracle_lab_host_map_mode=dataguard
  -e oracle_db_manage_apply_instance_overrides_require_dataguard=false
  -e oracle_restart_apply_instance_overrides_require_dataguard=false
  -e oracle_service_apply_instance_overrides_require_dataguard=false
)

for play in "${SITE_PLAYS[@]}"; do
  step "2/8 run ${play}"
  case "${play}" in
    playbooks/07-patch.yml|playbooks/07-patch-grid.yml)
      run_pb "${COMMON_E[@]}" "${play}" -e oracle_patch_apply_enabled=true
      ;;
    playbooks/03-create-instance.yml|playbooks/04-register-restart.yml)
      run_pb "${COMMON_E[@]}" "${play}"
      ;;
    *)
      run_pb "${COMMON_E[@]}" "${play}"
      ;;
  esac
done

# ── 3. Install second homes @ 19.31 (standalone, no cutover) ───────────
step "3/8 Install dbhome_2 @ 19.31 for standalone duper+fluff (DB stays on dbhome_1)"
STANDALONE_H1="$(write_standalone_vars dbhome_1 /tmp/e2e-standalone-home1.yml)"

run_pb -i "${INV}" -e @"${STANDALONE_H1}" --limit superdb1 \
  playbooks/07-upgrade-dual-db-prepare.yml \
  -e oracle_patch_dual_home_suffix=dbhome_2 \
  -e oracle_patch_apply_enabled=true \
  -e oracle_upgrade_prepare_force_rebuild=true \
  -e "oracle_patch_db_zip=${BASE_DB_ZIP}" \
  -e "oracle_patch_zip=${BASE_DB_ZIP}" \
  -e "oracle_patch_apply_component_path=${BASE_DB_COMPONENT}" \
  -e "oracle_upgrade_release_update=${BASE_RU}" \
  -e "oracle_upgrade_db_ru_patch_id=${BASE_PATCH_ID}" \
  -e "oracle_upgrade_db_ru_component_path=${BASE_DB_COMPONENT}"

# ── 4. Dual-home upgrade standalone → 19.32 ────────────────────────────
step "4/8 Dual-home upgrade duper+fluff to 19.32"

# 4a: rebuild unused home2 @ 19.32 (force), no switch
run_pb -i "${INV}" -e @"${STANDALONE_H1}" --limit superdb1 \
  playbooks/07-upgrade-dual-db-prepare.yml \
  -e oracle_patch_dual_home_suffix=dbhome_2 \
  -e oracle_patch_apply_enabled=true \
  -e oracle_upgrade_prepare_force_rebuild=true \
  -e "oracle_patch_db_zip=${UPG_DB_ZIP}" \
  -e "oracle_patch_zip=${UPG_DB_ZIP}" \
  -e "oracle_patch_apply_component_path=${UPG_DB_COMPONENT}"

# 4b: cutover to home2
run_pb -i "${INV}" -e @"${STANDALONE_H1}" --limit superdb1 \
  playbooks/07-upgrade-dual-db-cutover.yml \
  -e oracle_patch_dual_home_suffix=dbhome_2 \
  -e oracle_upgrade_cutover_execute=true \
  -e oracle_upgrade_cutover_confirm=CUTOVER_TO_UPGRADE_HOME \
  -e "oracle_patch_db_zip=${UPG_DB_ZIP}" \
  -e "oracle_patch_zip=${UPG_DB_ZIP}" \
  -e "oracle_patch_apply_component_path=${UPG_DB_COMPONENT}"

# 4c: rebuild home1 @ 19.32 while DBs on home2
STANDALONE_H2="$(write_standalone_vars dbhome_2 /tmp/e2e-standalone-home2.yml)"
run_pb -i "${INV}" -e @"${STANDALONE_H2}" --limit superdb1 \
  playbooks/07-upgrade-dual-db-prepare.yml \
  -e oracle_patch_dual_home_suffix=dbhome_1 \
  -e oracle_patch_apply_enabled=true \
  -e oracle_upgrade_prepare_force_rebuild=true \
  -e "oracle_patch_db_zip=${UPG_DB_ZIP}" \
  -e "oracle_patch_zip=${UPG_DB_ZIP}" \
  -e "oracle_patch_apply_component_path=${UPG_DB_COMPONENT}"

# 4d: cutover back to home1
run_pb -i "${INV}" -e @"${STANDALONE_H2}" --limit superdb1 \
  playbooks/07-upgrade-dual-db-cutover.yml \
  -e oracle_patch_dual_home_suffix=dbhome_1 \
  -e oracle_upgrade_cutover_execute=true \
  -e oracle_upgrade_cutover_confirm=CUTOVER_TO_UPGRADE_HOME \
  -e "oracle_patch_db_zip=${UPG_DB_ZIP}" \
  -e "oracle_patch_zip=${UPG_DB_ZIP}" \
  -e "oracle_patch_apply_component_path=${UPG_DB_COMPONENT}"

# ── 5. Data Guard super: no SF for combo packages ──────────────────────
# 19.32 media is an OJVM+DB RU combo — not SF as a whole. Apply combos
# together (dual-home prepare/cutover or downtime), not SF RU then OJVM.
# Standby-first remains for fully SF-eligible zips only.
step "5/8 SKIP super standby-first (combo policy: apply OJVM+RU together via dual-home/downtime)"
echo "[e2e] Combo zip ${UPG_DB_ZIP} is not standby-first installable as a unit."
echo "[e2e] Standalone dual-home upgrade already covered duper/fluff @ 19.32."
echo "[e2e] For DG super + combo, use playbooks/07-upgrade-dual-db-downtime.yml"
echo "[e2e] (or dual-home prepare on both DG nodes) — not run-standbyfirst-apply.sh."

# ── 6. Warm Data Guard switchover before pytest ────────────────────────
# First post-upgrade broker switchover under MaxAvailability can spend many
# minutes in CRS restart of the old primary. Running one cycle here warms the
# path and leaves roles on super so test_manual_switchover is not the cold start.
step "6/8 Warm Data Guard switchover (super -> super_sby -> super)"
run_pb "${COMMON_E[@]}" playbooks/05-dataguard.yml \
  -e oracle_dataguard_prepare_primary=false \
  -e oracle_dataguard_prepare_standby=false \
  -e oracle_dataguard_duplicate_standby=false \
  -e oracle_dataguard_configure_broker=false \
  -e oracle_dataguard_run_switchover=true \
  -e oracle_dataguard_switchover_target=super_sby
run_pb "${COMMON_E[@]}" playbooks/05-dataguard.yml \
  -e oracle_dataguard_prepare_primary=false \
  -e oracle_dataguard_prepare_standby=false \
  -e oracle_dataguard_duplicate_standby=false \
  -e oracle_dataguard_configure_broker=false \
  -e oracle_dataguard_run_switchover=true \
  -e oracle_dataguard_switchover_target=super

# ── 7. Automatic startup proof ───────────────────────────────────────────
step "7/8 Power-cycle and verify automatic startup"
./lab/scripts/lab-down.sh
./lab/scripts/lab-up.sh
./lab/scripts/update-hosts.sh --dg --multi
./scripts/verify-lab-autostart.sh

if [ "${SKIP_TESTS}" != "1" ]; then
  step "8/8 Full pytest suite"
  export ORACLE_TEST_REQUIRE_LAB=1
  ./scripts/run-tests.sh tests/ -v --tb=short --require-lab || {
    echo "ERROR: pytest reported failures (see log)" >&2
    exit 1
  }
else
  step "8/8 SKIP tests"
fi

step "E2E COMPLETE $(date -Is)"
echo "DONE"
echo "Log: ${LOG}"
